/* eslint-disable react/react-in-jsx-scope */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/app/[lang]/components/Header'
import Footer from '@/app/[lang]/components/Footer'
import { ReduxProvider } from '@/redux/provider'
import { i18n, type Locale } from "../../../i18n-config";
import { getDictionary } from '../../../get-dictionary'

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params: { lang }
}: {
  children: React.ReactNode,
  params: { lang: Locale }
}) {
  const dictionary = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body className={inter.className}>
        <ReduxProvider>
          <Header dictionary={dictionary['home-page']} params={lang} />
          <div>{children}</div>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
